[package]
name = "redis"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
async-trait = "0.1"
bytes = "1"
dashmap = "6"
futures = "0.3"
gc-arena = "0.5.3"
kv = { path = "../kv" }
piccolo = "0.3.3"
rand = "0.9"
rmpv = "1"
serde_json = "1"
sha1 = "0.10"
thiserror = "1"
tokio = { version = "1", features = ["net", "io-util", "rt", "sync", "time"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-util = { version = "0.7", features = ["codec"] }

[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["macros", "time"] }
