blank_issues_enabled: false
contact_links:
  - name: Questions & discussion
    url: https://discord.gg/WWE4PWVnb2
    about: For usage questions or general discussion rather than a specific bug or gap