[package]
name = "kv"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
async-trait = "0.1"
fjall = "3.1"
metrics = "0.24"
slatedb = { version = "0.16", features = ["aws", "foyer", "compression"] }
slatedb-common = "0.16"
thiserror = "2.0.20"

[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
