name: CI

on:
  pull_request:
    branches: [master]

jobs:
  validate_goreleaser:
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    steps:
      - uses: useblacksmith/checkout@v1
      - uses: goreleaser/goreleaser-action@v7
        with:
          args: check
  test:
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    steps:
      - uses: useblacksmith/checkout@v1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false # use Blacksmith's caching instead
      - uses: taiki-e/install-action@cargo-audit
      - name: Sticky disk - cargo registry
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-cargo-registry
          path: ~/.cargo/registry
      - name: Sticky disk - cargo git
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-cargo-git
          path: ~/.cargo/git
      - name: Sticky disk - target
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-cargo-target
          path: target
      - uses: denoland/setup-deno@v2
        with:
          deno-version: lts
      - name: Build, unit tests, and integration tests
        run: |
          cargo audit
          cargo clippy
          ./run-tests.sh
